server:
  port: 8081

spring:
  # Spring AI 配置 (以阿里云百炼为例，通常兼容 OpenAI 格式)
  ai:
    openai:
      api-key: sk-571293b31f4d43efb883baef316b0b11
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen3.6-plus # 你想用的模型
          temperature: 0.1 # 温度越低随机性越低 内容审核不需要高随机性
          response-format:
            type: json_object # 响应格式 让模型返回 JSON 而不是返回markdown
  # 自定义审核配置
  audit:
    max-retry-times: 3 # 最大重试次数

  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,templates/**
  application:
    name: thumb-backend
  mvc:
    servlet:
      path: /api
  # Tomcat 线程池优化
  tomcat:
    threads:
      max: 1000
      min-spare: 200
    max-connections: 10000
    accept-count: 1000
  data:
    redis:
      database: 0
      host: 192.168.192.130
      password:
      timeout: 3000
      port: 6379
      lettuce:
        pool:
          max-active: 500
          max-idle: 100
          min-idle: 50
          max-wait: 3000ms
  datasource:
    url: jdbc:mysql://localhost:3306/nexus_ai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 600000
  session:
    timeout: 86400s
    redis:
      serializer-type: json

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    rewriteBatchedStatements: true

rocketmq:
  name-server: 192.168.192.130:9876  # 你的Linux服务器IP
  producer:
    group: nexus-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2

# 自定义审核配置
audit:
  max-retry-times: 3 # 最大重试次数

# pulsar配置
#  pulsar:
#    producer:
#      batching-enabled: true
#      batching-max-messages: 1000
#      batching-max-publish-delay: 5ms
#      batching-max-size: 131072
#      compression-type: LZ4
#      send-timeout: 5000ms
#    client:
#      service-url: pulsar://192.168.192.130:6650
#    listener:
#      concurrency: 10

# 整合 Prometheus + Grafana
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, prometheus
#  metrics:
#    distribution:
#      percentiles:
#        http:
#          server:
#            requests: 0.5, 0.75, 0.9, 0.95, 0.99
